# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 700)
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        MainWindow.setStyleSheet("QStatusBar\n"
"{\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color :rgb(255, 0, 0) ;\n"
"border :3px solid gray;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1101, 671))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 550, 281, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(10, 290, 1081, 231))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidget.setFont(font)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 1061, 131))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(520, 30, 101, 31))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 131, 31))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 81, 31))
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(650, 40, 71, 31))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(110, 30, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit.setFont(font)
        self.lineEdit.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Egypt))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 80, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(600, 30, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(570, 80, 111, 41))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(720, 80, 111, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setGeometry(QtCore.QRect(960, 70, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setText("")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_16.setGeometry(QtCore.QRect(940, 10, 101, 41))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_17.setGeometry(QtCore.QRect(570, 80, 111, 41))
        self.pushButton_17.setCheckable(True)
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_2.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_8.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.label_25.raise_()
        self.pushButton_16.raise_()
        self.pushButton_17.raise_()
        self.lineEdit_3.raise_()
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 140, 1071, 151))
        self.groupBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 91, 31))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(340, 30, 71, 31))
        self.label_6.setObjectName("label_6")
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setGeometry(QtCore.QRect(490, 30, 51, 31))
        self.label_22.setObjectName("label_22")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(70, 30, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(390, 30, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(530, 30, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(700, 30, 71, 31))
        self.label_9.setObjectName("label_9")
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(550, 30, 71, 31))
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(770, 30, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_6.setText("")
        self.lineEdit_6.setCursorPosition(0)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(70, 90, 591, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 90, 91, 31))
        self.label_7.setObjectName("label_7")
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        self.label_32.setGeometry(QtCore.QRect(780, 100, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setText("")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(740, 100, 141, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_44 = QtWidgets.QLabel(self.groupBox_2)
        self.label_44.setGeometry(QtCore.QRect(550, 100, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setText("")
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.pushButton_29 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_29.setGeometry(QtCore.QRect(890, 30, 71, 51))
        self.pushButton_29.setObjectName("pushButton_29")
        self.label_44.raise_()
        self.label_23.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.label_22.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_5.raise_()
        self.label_9.raise_()
        self.lineEdit_6.raise_()
        self.label_7.raise_()
        self.label_32.raise_()
        self.pushButton.raise_()
        self.pushButton_29.raise_()
        self.lineEdit_10.raise_()
        self.comboBox.raise_()
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_15.setGeometry(QtCore.QRect(10, 550, 91, 51))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_18.setGeometry(QtCore.QRect(990, 550, 91, 61))
        self.pushButton_18.setObjectName("pushButton_18")
        self.label_38 = QtWidgets.QLabel(self.tab_2)
        self.label_38.setGeometry(QtCore.QRect(690, 520, 151, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("QLabel\n"
"{    font: 75 14pt \"MS Shell Dlg 2\";\n"
"color : rgb(255, 0, 0)\n"
"\n"
"}")
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.pushButton_28 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_28.setGeometry(QtCore.QRect(120, 550, 91, 61))
        self.pushButton_28.setObjectName("pushButton_28")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_13)
        self.tableWidget_6.setGeometry(QtCore.QRect(10, 100, 271, 421))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget_6.setFont(font)
        self.tableWidget_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_6.setAutoFillBackground(False)
        self.tableWidget_6.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_6.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(2)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        self.label_39 = QtWidgets.QLabel(self.tab_13)
        self.label_39.setGeometry(QtCore.QRect(40, 30, 131, 31))
        self.label_39.setObjectName("label_39")
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_24.setGeometry(QtCore.QRect(800, 30, 121, 51))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_26 = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_26.setGeometry(QtCore.QRect(530, 540, 201, 51))
        self.pushButton_26.setObjectName("pushButton_26")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_18.setGeometry(QtCore.QRect(500, 30, 131, 41))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_17.setGeometry(QtCore.QRect(150, 30, 231, 41))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_40 = QtWidgets.QLabel(self.tab_13)
        self.label_40.setGeometry(QtCore.QRect(420, 30, 131, 31))
        self.label_40.setObjectName("label_40")
        self.pushButton_25 = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_25.setGeometry(QtCore.QRect(80, 550, 121, 51))
        self.pushButton_25.setObjectName("pushButton_25")
        self.tableWidget_7 = QtWidgets.QTableWidget(self.tab_13)
        self.tableWidget_7.setGeometry(QtCore.QRect(320, 100, 751, 421))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tableWidget_7.setFont(font)
        self.tableWidget_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_7.setAutoFillBackground(False)
        self.tableWidget_7.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_7.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(5)
        self.tableWidget_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(4, item)
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_23.setGeometry(QtCore.QRect(660, 30, 121, 51))
        self.pushButton_23.setObjectName("pushButton_23")
        self.label_41 = QtWidgets.QLabel(self.tab_13)
        self.label_41.setGeometry(QtCore.QRect(670, 50, 81, 31))
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.tableWidget_6.raise_()
        self.label_39.raise_()
        self.pushButton_24.raise_()
        self.pushButton_26.raise_()
        self.lineEdit_18.raise_()
        self.lineEdit_17.raise_()
        self.label_40.raise_()
        self.pushButton_25.raise_()
        self.tableWidget_7.raise_()
        self.label_41.raise_()
        self.pushButton_23.raise_()
        self.tabWidget.addTab(self.tab_13, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_12.setGeometry(QtCore.QRect(410, 20, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        self.label_26.setGeometry(QtCore.QRect(250, 30, 121, 31))
        self.label_26.setObjectName("label_26")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 80, 1091, 521))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_8)
        self.comboBox_2.setGeometry(QtCore.QRect(453, 90, 311, 51))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_11 = QtWidgets.QLabel(self.tab_8)
        self.label_11.setGeometry(QtCore.QRect(283, 190, 111, 31))
        self.label_11.setObjectName("label_11")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_7.setGeometry(QtCore.QRect(453, 180, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setMaxLength(20)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_5.setGeometry(QtCore.QRect(510, 310, 151, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_10 = QtWidgets.QLabel(self.tab_8)
        self.label_10.setGeometry(QtCore.QRect(283, 90, 181, 31))
        self.label_10.setObjectName("label_10")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.label_31 = QtWidgets.QLabel(self.tab_10)
        self.label_31.setGeometry(QtCore.QRect(123, 110, 181, 31))
        self.label_31.setObjectName("label_31")
        self.label_33 = QtWidgets.QLabel(self.tab_10)
        self.label_33.setGeometry(QtCore.QRect(123, 210, 111, 31))
        self.label_33.setObjectName("label_33")
        self.pushButton_21 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_21.setGeometry(QtCore.QRect(480, 320, 151, 51))
        self.pushButton_21.setObjectName("pushButton_21")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_10)
        self.comboBox_4.setGeometry(QtCore.QRect(230, 110, 241, 51))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_10)
        self.comboBox_5.setGeometry(QtCore.QRect(720, 110, 241, 51))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_34 = QtWidgets.QLabel(self.tab_10)
        self.label_34.setGeometry(QtCore.QRect(613, 210, 111, 31))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab_10)
        self.label_35.setGeometry(QtCore.QRect(613, 110, 181, 31))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_10)
        self.label_36.setGeometry(QtCore.QRect(310, 60, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_10)
        self.label_37.setGeometry(QtCore.QRect(760, 60, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_5 = QtWidgets.QLabel(self.tab_10)
        self.label_5.setGeometry(QtCore.QRect(240, 130, 55, 16))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_15.setGeometry(QtCore.QRect(230, 200, 241, 51))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_16.setGeometry(QtCore.QRect(720, 200, 241, 51))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_31.raise_()
        self.label_33.raise_()
        self.pushButton_21.raise_()
        self.comboBox_5.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.label_5.raise_()
        self.lineEdit_15.raise_()
        self.lineEdit_16.raise_()
        self.comboBox_4.raise_()
        self.tabWidget_3.addTab(self.tab_10, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_13.setGeometry(QtCore.QRect(490, 110, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_27 = QtWidgets.QLabel(self.tab_9)
        self.label_27.setGeometry(QtCore.QRect(330, 120, 151, 31))
        self.label_27.setObjectName("label_27")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_14.setGeometry(QtCore.QRect(490, 180, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_28 = QtWidgets.QLabel(self.tab_9)
        self.label_28.setGeometry(QtCore.QRect(330, 190, 131, 31))
        self.label_28.setObjectName("label_28")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_14.setGeometry(QtCore.QRect(530, 280, 151, 51))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_22.setGeometry(QtCore.QRect(30, 360, 121, 71))
        self.pushButton_22.setObjectName("pushButton_22")
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 20, 1081, 621))
        self.tabWidget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 140, 1071, 411))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setGeometry(QtCore.QRect(10, 30, 131, 31))
        self.label_12.setObjectName("label_12")
        self.dateEdit = QtWidgets.QDateEdit(self.tab_5)
        self.dateEdit.setGeometry(QtCore.QRect(720, 20, 151, 31))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.tab_5)
        self.dateEdit_2.setGeometry(QtCore.QRect(500, 20, 151, 31))
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        self.label_13.setGeometry(QtCore.QRect(680, 20, 51, 31))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_5)
        self.label_14.setGeometry(QtCore.QRect(430, 20, 51, 31))
        self.label_14.setObjectName("label_14")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_6.setGeometry(QtCore.QRect(-10, 550, 111, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_9.setGeometry(QtCore.QRect(500, 90, 141, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_8.setGeometry(QtCore.QRect(100, 20, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_20 = QtWidgets.QLabel(self.tab_5)
        self.label_20.setGeometry(QtCore.QRect(20, 90, 131, 31))
        self.label_20.setObjectName("label_20")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_11.setGeometry(QtCore.QRect(100, 80, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_19.setGeometry(QtCore.QRect(690, 90, 131, 41))
        self.pushButton_19.setObjectName("pushButton_19")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.dateEdit_4 = QtWidgets.QDateEdit(self.tab_6)
        self.dateEdit_4.setGeometry(QtCore.QRect(650, 30, 151, 31))
        self.dateEdit_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateEdit_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dateEdit_4.setCalendarPopup(True)
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.label_17 = QtWidgets.QLabel(self.tab_6)
        self.label_17.setGeometry(QtCore.QRect(20, 40, 131, 31))
        self.label_17.setObjectName("label_17")
        self.label_15 = QtWidgets.QLabel(self.tab_6)
        self.label_15.setGeometry(QtCore.QRect(560, 30, 51, 31))
        self.label_15.setObjectName("label_15")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 150, 1071, 401))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        self.label_16 = QtWidgets.QLabel(self.tab_6)
        self.label_16.setGeometry(QtCore.QRect(560, 80, 51, 31))
        self.label_16.setObjectName("label_16")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_9.setGeometry(QtCore.QRect(80, 40, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_7.setGeometry(QtCore.QRect(-10, 550, 111, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_10.setGeometry(QtCore.QRect(100, 100, 141, 41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.dateEdit_3 = QtWidgets.QDateEdit(self.tab_6)
        self.dateEdit_3.setGeometry(QtCore.QRect(650, 80, 151, 31))
        self.dateEdit_3.setCalendarPopup(True)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_20.setGeometry(QtCore.QRect(280, 100, 131, 41))
        self.pushButton_20.setObjectName("pushButton_20")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_11.setGeometry(QtCore.QRect(630, 0, 151, 61))
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_18 = QtWidgets.QLabel(self.tab_7)
        self.label_18.setGeometry(QtCore.QRect(50, 20, 51, 31))
        self.label_18.setObjectName("label_18")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_4.setGeometry(QtCore.QRect(0, 70, 1071, 481))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidget_4.setFont(font)
        self.tableWidget_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_4.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_4.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(9)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_4.setHorizontalHeaderItem(8, item)
        self.label_19 = QtWidgets.QLabel(self.tab_7)
        self.label_19.setGeometry(QtCore.QRect(320, 20, 51, 31))
        self.label_19.setObjectName("label_19")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_8.setGeometry(QtCore.QRect(-10, 550, 111, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.dateEdit_5 = QtWidgets.QDateEdit(self.tab_7)
        self.dateEdit_5.setGeometry(QtCore.QRect(360, 20, 151, 31))
        self.dateEdit_5.setCalendarPopup(True)
        self.dateEdit_5.setObjectName("dateEdit_5")
        self.dateEdit_6 = QtWidgets.QDateEdit(self.tab_7)
        self.dateEdit_6.setGeometry(QtCore.QRect(120, 20, 151, 31))
        self.dateEdit_6.setCalendarPopup(True)
        self.dateEdit_6.setObjectName("dateEdit_6")
        self.label_45 = QtWidgets.QLabel(self.tab_7)
        self.label_45.setGeometry(QtCore.QRect(830, 20, 131, 31))
        self.label_45.setObjectName("label_45")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_5.setGeometry(QtCore.QRect(0, 80, 1071, 471))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidget_5.setFont(font)
        self.tableWidget_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(3)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        self.pushButton_13 = QtWidgets.QPushButton(self.tab)
        self.pushButton_13.setGeometry(QtCore.QRect(-10, 550, 111, 41))
        self.pushButton_13.setObjectName("pushButton_13")
        self.dateEdit_7 = QtWidgets.QDateEdit(self.tab)
        self.dateEdit_7.setGeometry(QtCore.QRect(320, 40, 151, 31))
        self.dateEdit_7.setCalendarPopup(True)
        self.dateEdit_7.setObjectName("dateEdit_7")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(20, 40, 51, 31))
        self.label_21.setObjectName("label_21")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab)
        self.pushButton_12.setGeometry(QtCore.QRect(780, 40, 141, 41))
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(280, 40, 51, 31))
        self.label_24.setObjectName("label_24")
        self.dateEdit_8 = QtWidgets.QDateEdit(self.tab)
        self.dateEdit_8.setGeometry(QtCore.QRect(80, 40, 151, 31))
        self.dateEdit_8.setCalendarPopup(True)
        self.dateEdit_8.setObjectName("dateEdit_8")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab)
        self.comboBox_3.setGeometry(QtCore.QRect(520, 30, 191, 51))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.tabWidget_2.addTab(self.tab, "")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.tab_11)
        self.lcdNumber_4.setGeometry(QtCore.QRect(470, 360, 241, 171))
        self.lcdNumber_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.label_29 = QtWidgets.QLabel(self.tab_11)
        self.label_29.setGeometry(QtCore.QRect(170, 80, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_11)
        self.label_30.setGeometry(QtCore.QRect(120, 420, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.tab_11)
        self.lcdNumber_3.setGeometry(QtCore.QRect(480, 30, 231, 171))
        self.lcdNumber_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.label_42 = QtWidgets.QLabel(self.tab_11)
        self.label_42.setGeometry(QtCore.QRect(470, 270, 51, 31))
        self.label_42.setObjectName("label_42")
        self.pushButton_27 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_27.setGeometry(QtCore.QRect(750, 270, 141, 41))
        self.pushButton_27.setObjectName("pushButton_27")
        self.dateEdit_9 = QtWidgets.QDateEdit(self.tab_11)
        self.dateEdit_9.setGeometry(QtCore.QRect(270, 270, 151, 31))
        self.dateEdit_9.setCalendarPopup(True)
        self.dateEdit_9.setObjectName("dateEdit_9")
        self.dateEdit_10 = QtWidgets.QDateEdit(self.tab_11)
        self.dateEdit_10.setGeometry(QtCore.QRect(510, 270, 151, 31))
        self.dateEdit_10.setCalendarPopup(True)
        self.dateEdit_10.setObjectName("dateEdit_10")
        self.label_43 = QtWidgets.QLabel(self.tab_11)
        self.label_43.setGeometry(QtCore.QRect(210, 270, 51, 31))
        self.label_43.setObjectName("label_43")
        self.tabWidget.addTab(self.tab_11, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Save Patient    F10"))
        self.pushButton_2.setShortcut(_translate("MainWindow", "F10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Drug"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Dose"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Fluid"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Volume"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Note"))
        self.groupBox.setTitle(_translate("MainWindow", "Patient Details"))
        self.label_2.setText(_translate("MainWindow", "Phone NO"))
        self.label.setText(_translate("MainWindow", "Patient Name"))
        self.label_3.setText(_translate("MainWindow", "Patient ID"))
        self.pushButton_3.setText(_translate("MainWindow", "Save"))
        self.pushButton_3.setShortcut(_translate("MainWindow", "F8"))
        self.pushButton_4.setText(_translate("MainWindow", "Clear"))
        self.pushButton_16.setText(_translate("MainWindow", "Today"))
        self.pushButton_17.setText(_translate("MainWindow", "Update"))
        self.pushButton_17.setShortcut(_translate("MainWindow", "F2"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Add Drug"))
        self.label_4.setText(_translate("MainWindow", "Drug"))
        self.label_6.setText(_translate("MainWindow", "Dose"))
        self.label_22.setText(_translate("MainWindow", "Fluid"))
        self.label_9.setText(_translate("MainWindow", "Volume"))
        self.label_7.setText(_translate("MainWindow", "Note"))
        self.pushButton.setText(_translate("MainWindow", "Add"))
        self.pushButton.setShortcut(_translate("MainWindow", "F9"))
        self.pushButton_29.setText(_translate("MainWindow", "Clear"))
        self.pushButton_15.setText(_translate("MainWindow", "Delete"))
        self.pushButton_18.setText(_translate("MainWindow", "New"))
        self.pushButton_18.setShortcut(_translate("MainWindow", "F1"))
        self.pushButton_28.setText(_translate("MainWindow", "Modify"))
        self.pushButton_28.setShortcut(_translate("MainWindow", "F1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Register Patient"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Visit"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date"))
        self.label_39.setText(_translate("MainWindow", "Patient Name"))
        self.pushButton_24.setText(_translate("MainWindow", "Clear"))
        self.pushButton_26.setText(_translate("MainWindow", "Delete All Patient Data"))
        self.label_40.setText(_translate("MainWindow", "Patient ID"))
        self.pushButton_25.setText(_translate("MainWindow", "DELETE VISIT"))
        item = self.tableWidget_7.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Drug"))
        item = self.tableWidget_7.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Dose"))
        item = self.tableWidget_7.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Fluid"))
        item = self.tableWidget_7.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Volume"))
        item = self.tableWidget_7.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Note"))
        self.pushButton_23.setText(_translate("MainWindow", "Search"))
        self.pushButton_23.setShortcut(_translate("MainWindow", "F10"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_13), _translate("MainWindow", "Patient Management"))
        self.label_26.setText(_translate("MainWindow", "Enter Password"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Chemotherapy drugs"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Supportive drugs"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Fluids"))
        self.label_11.setText(_translate("MainWindow", "Drug Name"))
        self.pushButton_5.setText(_translate("MainWindow", "Save"))
        self.pushButton_5.setShortcut(_translate("MainWindow", "F10"))
        self.label_10.setText(_translate("MainWindow", "Main Category"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Add drug"))
        self.label_31.setText(_translate("MainWindow", "Main Category"))
        self.label_33.setText(_translate("MainWindow", "Drug Name"))
        self.pushButton_21.setText(_translate("MainWindow", "Update"))
        self.pushButton_21.setShortcut(_translate("MainWindow", "F10"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Chemotherapy drugs"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Supportive drugs"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Fluids"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Chemotherapy drugs"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Supportive drugs"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "Fluids"))
        self.label_34.setText(_translate("MainWindow", "Drug Name"))
        self.label_35.setText(_translate("MainWindow", "Main Category"))
        self.label_36.setText(_translate("MainWindow", "Old Drug"))
        self.label_37.setText(_translate("MainWindow", "New drug"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("MainWindow", "Update Drug"))
        self.label_27.setText(_translate("MainWindow", "Enter New Password"))
        self.label_28.setText(_translate("MainWindow", "Enter Password Again"))
        self.pushButton_14.setText(_translate("MainWindow", "Save"))
        self.pushButton_14.setShortcut(_translate("MainWindow", "F10"))
        self.pushButton_22.setText(_translate("MainWindow", "Clear Database "))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "Change Password"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Add Drugs"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Drug"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Dose"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Fluid"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Volume"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Note"))
        self.label_12.setText(_translate("MainWindow", "Patient Name"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.dateEdit_2.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label_13.setText(_translate("MainWindow", "To"))
        self.label_14.setText(_translate("MainWindow", "From"))
        self.pushButton_6.setText(_translate("MainWindow", "To Excel"))
        self.pushButton_9.setText(_translate("MainWindow", "Search"))
        self.pushButton_9.setShortcut(_translate("MainWindow", "F10"))
        self.label_20.setText(_translate("MainWindow", "Patient ID"))
        self.pushButton_19.setText(_translate("MainWindow", "Clear"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Search For Patient "))
        self.dateEdit_4.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label_17.setText(_translate("MainWindow", "Drug"))
        self.label_15.setText(_translate("MainWindow", "From"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Drug"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Total Doses"))
        self.label_16.setText(_translate("MainWindow", "To"))
        self.pushButton_7.setText(_translate("MainWindow", "To Excel"))
        self.pushButton_10.setText(_translate("MainWindow", "Search"))
        self.pushButton_10.setShortcut(_translate("MainWindow", "F10"))
        self.dateEdit_3.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.pushButton_20.setText(_translate("MainWindow", "Clear"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Search For Drug"))
        self.pushButton_11.setText(_translate("MainWindow", "Search"))
        self.pushButton_11.setShortcut(_translate("MainWindow", "F12"))
        self.label_18.setText(_translate("MainWindow", "From"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Patient Name"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Patient Id"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Drug"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Dose"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Fluid"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Volume"))
        item = self.tableWidget_4.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Note"))
        item = self.tableWidget_4.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_4.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "C"))
        self.label_19.setText(_translate("MainWindow", "To"))
        self.pushButton_8.setText(_translate("MainWindow", "To Excel"))
        self.dateEdit_5.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.dateEdit_6.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label_45.setText(_translate("MainWindow", "Press F12 For Update "))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Search"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Drug Name"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Total Dose"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "NO"))
        self.pushButton_13.setText(_translate("MainWindow", "To Excel"))
        self.dateEdit_7.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label_21.setText(_translate("MainWindow", "From"))
        self.pushButton_12.setText(_translate("MainWindow", "Search"))
        self.pushButton_12.setShortcut(_translate("MainWindow", "F10"))
        self.label_24.setText(_translate("MainWindow", "To"))
        self.dateEdit_8.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Chemotherapy drugs"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Supportive drugs"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Fluids"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Dose"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Reports"))
        self.label_29.setText(_translate("MainWindow", "New Patient Today"))
        self.label_30.setText(_translate("MainWindow", "Old Patient "))
        self.label_42.setText(_translate("MainWindow", "To"))
        self.pushButton_27.setText(_translate("MainWindow", "Search"))
        self.pushButton_27.setShortcut(_translate("MainWindow", "F10"))
        self.dateEdit_9.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.dateEdit_10.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label_43.setText(_translate("MainWindow", "From"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "Statics"))
